#intellij?? static ??? ??? ? ??? ??? ?? ??? ??? ??? ?? ??? ??? ?? ?? ???.
#spring:
#  config:
#    activate:
#      on-profile: local
##  profiles:
##    active: local
#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: false
#  freemarker:
#    cache: false
#    suffix: .ftl # circular viewer ?? ??

spring:
  profiles:
    active: local
  redis:
    host: localhost
    port: 6379
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
    suffix: .ftl # circular viewer ?? ??

